stages:
  - image-build
  - apiwrap
  - fetch-scripts
  - build
  - analyze
  - test
  - docs
  - deploy

#=======================================================================================================================

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MACHINES_CONTAINER_REG:
    value: registry.gams.com/devel/machines
    description: "URL to the container registry of the machines repository"
  PF_CUSTOM_BRANCH:
    value: "master"
    description: "Name of custom branch, 0 if published distribution with version as specified should be taken or X.Y.Z"
  PF_BUILDS_WWW_PATH:
    value: $BUILDS_WWW_PATH
    description: "URL path prefix for builds server"
  PF_BUILDS_SSH_PORT:
    value: $BUILDS_SSH_PORT
    description: "Port used for SSH connection to builds server"
  PF_BUILDS_SSH_SERVER:
    value: $BUILDS_SSH_SERVER
    description: "URL of the build server"
  PF_BUILDS_SSH_USER:
    value: $BUILDS_SSH_USER
    description: "Username used for SSH connection to builds server"

#=======================================================================================================================

build-leg-image:
  stage: image-build
  when: manual
  tags: [linux]
  image:
    name: docker:20.10
  services:
    - docker:20.10-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build -t registry.gams.com/devel/gdx/leg/builder-gdx:latest ci/images/leg
    - docker push registry.gams.com/devel/gdx/leg/builder-gdx:latest

build-leg-analyze-image:
  stage: image-build
  when: manual
  tags: [linux]
  image:
    name: docker:20.10
  services:
    - docker:20.10-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build -t registry.gams.com/devel/gdx/leg/builder-analyze:latest ci/images/leg-analyze
    - docker push registry.gams.com/devel/gdx/leg/builder-analyze:latest

build-leg-deploy-image:
  stage: image-build
  when: manual
  tags: [linux]
  image:
    name: docker:20.10
  services:
    - docker:20.10-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build -t registry.gams.com/devel/gdx/leg/builder-deploy:latest ci/images/leg-deploy
    - docker push registry.gams.com/devel/gdx/leg/builder-deploy:latest

#=======================================================================================================================

apigenerator:
  stage: apiwrap
  when: always
  tags: [linux]
  dependencies: []
  image:
    name: registry.gams.com/devel/gdx/leg/builder-gdx:latest
    entrypoint: [ "" ]
  script:
    # first generate gdxapi.yaml from files in src/apiyaml and GDX main header file with doxy2yaml-tool
    - python3 src/doxy2yaml/doxy2yaml.py name=gdxapi header=../gdx.h indir=src/apiyaml outdir=`pwd`
    # somehow I need absolute path for apidef arg
    - GVERSIONMAJOR=45 GVERSIONMINOR=0 GVERSIONRELEASE=0 python3 src/apigenerator/src/mkapi.py --apidef `pwd`/gdxapi.yaml --outputpath apifiles/ --output cc cpplib
    - cp src/apigenerator/include/gc*.h apifiles
    - |
      for f in "gdxcc.h" "gdxcc.c" "gdxcclib.cpp" "gclgms.h"; do
        if diff apifiles/$f generated/$f; then
          echo "Warning: $f stored in repo and freshly generated differ!"
        fi
      done
  artifacts:
    name: apifiles
    expire_in: 2 hours
    paths: [ apifiles/* ]

#=======================================================================================================================

# also fetches zlib since CMake-build of doesn't automatigically gets its like the devel/products Makefile
fetch-ci-scripts:
  stage: fetch-scripts
  when: always
  tags: [linux]
  dependencies: []
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [ "" ]
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gams.com/devel/ciscripts.git scripts-repo
    - cp -R scripts-repo/ci .
    - git clone https://github.com/madler/zlib zlib
  artifacts:
    name: ci-scripts
    expire_in: 2 hours
    paths: [ci/*,zlib/*]

#=======================================================================================================================

build-leg:
  stage: build
  when: on_success
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  script:
    - cp apifiles/* src/
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON CMakeLists.txt
    - cmake --build . 2>&1 | tee build_log.txt
    - python3 ci/report_for_log.py gcc build_log.txt warnings.xml
  needs: [fetch-ci-scripts,apigenerator]
  artifacts:
    name: gdx-leg
    paths: [gdxtest,gdxwraptest,libgdxcclib64.so]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

build-deg:
  stage: build
  when: on_success
  tags: [macos]
  script:
    - cp apifiles/* src/
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_CXX_COMPILER=clang++ CMakeLists.txt
    - cmake --build . 2>&1 | tee build_log.txt
    - python3 ci/report_for_log.py clang build_log.txt warnings.xml
  needs: [fetch-ci-scripts,apigenerator]
  artifacts:
    name: gdx-deg
    paths: [gdxtest,gdxwraptest,libgdxcclib64.dylib]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

build-dac:
  stage: build
  when: on_success
  tags: [macos-arm64]
  script:
    - cp apifiles/* src/
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_CXX_COMPILER=clang++ CMakeLists.txt
    - cmake --build . 2>&1 | tee build_log.txt
    - python3 ci/report_for_log.py clang build_log.txt warnings.xml
  needs: [fetch-ci-scripts,apigenerator]
  artifacts:
    name: gdx-dac
    paths: [gdxtest,gdxwraptest,libgdxcclib64.dylib]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

build-wei:
  stage: build
  when: on_success
  tags: [windows]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
  script:
    - cp apifiles/* src/
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON CMakeLists.txt
    - cmake --build  . --config Release -- -m | Tee-Object -FilePath 'build_log.txt'
    - python ci/report_for_log.py msvc build_log.txt warnings.xml
  needs: [fetch-ci-scripts,apigenerator]
  artifacts:
    name: gdx-wei
    paths: [Release]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

#=======================================================================================================================

codechecker-leg:
  stage: analyze
  tags: [linux]
  image:
    name: registry.gams.com/devel/gdx/leg/builder-analyze:latest
    entrypoint: [""]
  needs: [fetch-ci-scripts,apigenerator]
  allow_failure: false
  script:
    - cp apifiles/* src/
    - cmake -DCMAKE_C_COMPILER=/usr/bin/clang-10 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON CMakeLists.txt
    - |
      CodeChecker log -b "make -j4" -o compilation_database.json &&
      CodeChecker analyze --analyzers clang-tidy clangsa -o reports compilation_database.json &&
      CodeChecker parse --trim-path-prefix $(pwd) -e codeclimate reports > gl-code-quality-report.json || true
  after_script:
    - cat gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
    expire_in: '2 mos'

#=======================================================================================================================

test-leg:
  stage: test
  when: on_success
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  needs: [build-leg]
  script:
    - ./gdxtest --reporters=junit --out=doctest_results_linux.xml
    - LD_LIBRARY_PATH=`pwd` ./gdxwraptest --reporters=junit --out=doctest_results_wrap_linux.xml
  artifacts:
    name: unittest-results-linux
    paths: [./*.xml]
    expire_in: 2 hours
    reports:
      junit: doctest_results_*linux.xml

test-deg:
  stage: test
  when: on_success
  tags: [macos]
  needs: [build-deg]
  script:
    - ./gdxtest --reporters=junit --out=doctest_results_deg.xml
    - ./gdxwraptest --reporters=junit --out=doctest_results_wrap_deg.xml
  artifacts:
    name: unittest-results-deg
    paths: [./*.xml]
    reports:
      junit: doctest_results_*deg.xml

test-dac:
  stage: test
  when: on_success
  tags: [macos-arm64]
  needs: [build-dac]
  script:
    - ./gdxtest --reporters=junit --out=doctest_results_dac.xml
    - ./gdxwraptest --reporters=junit --out=doctest_results_wrap_dac.xml
  artifacts:
    name: unittest-results-dac
    paths: [./*.xml]
    reports:
      junit: doctest_results_*dac.xml

test-wei:
  stage: test
  when: on_success
  tags: [windows]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
  needs: [build-wei]
  script:
    - ./Release/gdxtest --reporters=junit --out=doctest_results_windows.xml
    - ./Release/gdxwraptest --reporters=junit --out=doctest_results_wrap_windows.xml
  artifacts:
    name: unittest-results-windows
    paths: [./*.xml]
    reports:
      junit: doctest_results_*windows.xml

#=======================================================================================================================

doxygen-html:
  stage: docs
  when: always
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  script:
    - doxygen
  artifacts:
    name: doxygen-html-docs
    paths: [docs/html]
    expire_in: 1 day

#=======================================================================================================================

deploy-github:
  when: always
  stage: deploy
  tags: [linux]
  needs: [build-leg, build-dac, build-wei, apigenerator]
  image:
    name: registry.gams.com/devel/gdx/leg/builder-deploy:latest
    entrypoint: [""]   # prevent startup.sh
  script:
    - ls
    - PATH="/opt/github-release:${PATH}"
    - github-release
    - cp Release/gdxcclib64.dll .
    - cp apifiles/*.h apifiles/*.c apifiles/*.cpp .
#    - GITHUB_TOKEN=${GITHUB_TOKEN} github-release -v release -u GAMS-dev -r gdx -t example-tag -d "some text." -n "Example release"
    - |
      for fn in libgdxcclib64.so gdxcclib64.dll libgdxcclib64.dylib gclgms.h gcmutex.h gdxcc.h gdxcc.c gdxcclib.cpp
      do
        GITHUB_TOKEN=${GITHUB_TOKEN} github-release -v upload -R -u GAMS-dev -r gdx -t example-tag -n $fn -f $fn
      done
