stages:
  - fetch-scripts
  - install-gams
  - build
  - test

variables:
  MACHINES_CONTAINER_REG:
    value: registry.gams.com/devel/machines
    description: "URL to the container registry of the machines repository"
  PF_CUSTOM_BRANCH:
    value: "master"
    description: "Name of custom branch or 0 if published distribution with version as specified should be taken"
  PF_BUILDS_WWW_PATH:
    value: $BUILDS_WWW_PATH
    description: "URL path prefix for builds server"
  PF_BUILDS_SSH_PORT:
    value: $BUILDS_SSH_PORT
    description: "Port used for SSH connection to builds server"
  PF_BUILDS_SSH_SERVER:
    value: $BUILDS_SSH_SERVER
    description: "URL of the build server"
  PF_BUILDS_SSH_USER:
    value: $BUILDS_SSH_USER
    description: "Username used for SSH connection to builds server"

# also fetches zlib since CMake-build of doesn't automatigically gets its like the devel/products Makefile
fetch-ci-scripts:
  stage: fetch-scripts
  when: always
  tags: [linux]
  dependencies: []
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [ "" ]
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gams.com/devel/ciscripts.git scripts-repo
    - cp -R scripts-repo/ci .
    - git clone  https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gams.com/devel/gmszlib.git zlib
  artifacts:
    name: ci-scripts
    expire_in: 2 hours
    paths: [ci/*,zlib/*]

build-leg:
  stage: build
  when: on_success
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON CMakeLists.txt
    - cmake --build . 2>&1 | tee build_log.txt
    - python3 ci/report_for_log.py gcc build_log.txt warnings.xml
  needs: [fetch-ci-scripts]
  artifacts:
    name: gdx-leg
    paths: [gdxtest]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

build-deg:
  stage: build
  when: on_success
  tags: [macos]
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_CXX_COMPILER=clang++ CMakeLists.txt
    - cmake --build . 2>&1 | tee build_log.txt
    - python3 ci/report_for_log.py clang build_log.txt warnings.xml
  needs: [fetch-ci-scripts]
  artifacts:
    name: gdx-deg
    paths: [gdxtest]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

build-dac:
  stage: build
  when: on_success
  tags: [macos-arm64]
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_CXX_COMPILER=clang++ CMakeLists.txt
    - cmake --build . 2>&1 | tee build_log.txt
    - python3 ci/report_for_log.py clang build_log.txt warnings.xml
  needs: [fetch-ci-scripts]
  artifacts:
    name: gdx-dac
    paths: [gdxtest]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

build-wei:
  stage: build
  when: on_success
  tags: [windows]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON CMakeLists.txt
    - cmake --build  . --config Release -- -m | Tee-Object -FilePath 'build_log.txt'
    - python ci/report_for_log.py msvc build_log.txt warnings.xml
  needs: [fetch-ci-scripts]
  artifacts:
    name: gdx-wei
    paths: [Release]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

test-leg:
  stage: test
  when: on_success
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  needs: [build-leg]
  script:
    - ./gdxtest -tce=*trace* --reporters=junit --out=doctest_results_linux.xml
  artifacts:
    name: unittest-results-linux
    paths: [doctest_results_linux.xml]
    expire_in: 2 hours
    reports:
      junit: doctest_results_linux.xml
