stages:
  - build
  - test

build-leg:
  stage: build
  when: always
  tags: [linux]
  image:
    name: registry.gams.com/devel/machines/leg/builder-full:latest
    entrypoint: [""]
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON CMakeLists.txt
    - cmake --build .
  artifacts:
    name: gdx-leg
    paths: [gdxtest]
    expire_in: 2 hours

test-leg:
  stage: test
  when: on_success
  tags: [linux]
  image:
    name: registry.gams.com/devel/machines/leg/builder-full:latest
    entrypoint: [""]
  needs: [build-leg]
  script:
    - ./gdxtest -tce=*trace* --reporters=junit --out=doctest_results_linux.xml
  artifacts:
    name: unittest-results-linux
    paths: [doctest_results_linux.xml]
    expire_in: 2 hours
    reports:
      junit: doctest_results_linux.xml
