# also includes unused sources (modules and headers)
set(base-units-all
        # runtime library
        src/rtl/p3library.cpp
		src/rtl/p3library.hpp
        src/rtl/p3process.cpp
		src/rtl/p3process.hpp
        src/rtl/stdthread.cpp
		src/rtl/stdthread.hpp
        src/rtl/p3utils.cpp
		src/rtl/p3utils.hpp
        src/rtl/sysutils_p3.cpp
		src/rtl/sysutils_p3.hpp
        src/rtl/system_p3.cpp
		src/rtl/system_p3.hpp
        src/rtl/p3platform.cpp
		src/rtl/p3platform.hpp
        src/rtl/math_p3.cpp
		src/rtl/math_p3.hpp
        src/rtl/idglobal_p3.cpp
		src/rtl/idglobal_p3.hpp
        src/rtl/p3io.cpp
		src/rtl/p3io.hpp
        src/rtl/dtoaLoc.c
        src/rtl/dtoaLoc.h

        # global
        src/global/ctvproc.cpp
		src/global/ctvproc.hpp
		src/global/delphitypes.hpp
        src/global/gmslibname.cpp
		src/global/gmslibname.hpp
        src/global/gmsspecs.cpp
		src/global/gmsspecs.hpp
        src/global/unit.h
        src/global/modhead.cpp
		src/global/modhead.hpp

        # gdlib
        src/gdlib/batchalloc.hpp
        src/gdlib/charmaps.cpp
        src/gdlib/charmaps.hpp
        src/gdlib/cmdpar.cpp
        src/gdlib/cmdpar.hpp
        src/gdlib/datastorage.cpp
        src/gdlib/datastorage.hpp
        src/gdlib/dblutil.cpp
        src/gdlib/dblutil.hpp
        src/gdlib/gamsdirs.cpp
        src/gdlib/gamsdirs.hpp
        src/gdlib/gfileopen.cpp
        src/gdlib/gfileopen.hpp
        src/gdlib/glookup.cpp
        src/gdlib/glookup.hpp
        src/gdlib/gmacro.cpp
        src/gdlib/gmacro.hpp
        src/gdlib/gmsdata.cpp
        src/gdlib/gmsdata.hpp
        src/gdlib/gmsgen.hpp
        src/gdlib/gmsglob.cpp
        src/gdlib/gmsglob.hpp
        src/gdlib/gmslist.cpp
		src/gdlib/gmslist.hpp
        src/gdlib/gmsobj.cpp
		src/gdlib/gmsobj.hpp
        src/gdlib/obfuscatestr.cpp
		src/gdlib/obfuscatestr.hpp
        src/gdlib/runner.cpp
		src/gdlib/runner.hpp
        src/gdlib/statlib.cpp
        src/gdlib/statlib.hpp
        src/gdlib/statlibobj.cpp
		src/gdlib/statlibobj.hpp
		src/gdlib/stattypes.hpp
        src/gdlib/xcompress.cpp
		src/gdlib/xcompress.hpp
        src/gdlib/gmsheapnew.cpp
        src/gdlib/gmsheapnew.hpp
        src/gdlib/strutilx.cpp
		src/gdlib/strutilx.hpp
        src/gdlib/strhash.cpp
		src/gdlib/strhash.hpp
		src/gdlib/gmsonly.hpp
        src/gdlib/gmsonly.cpp
)