set(base-units
        # runtime library
        src/rtl/p3library.cpp
        src/rtl/p3library.h
        src/rtl/p3process.cpp
        src/rtl/p3process.h
        src/rtl/stdthread.cpp
        src/rtl/stdthread.h
        src/rtl/p3utils.cpp
        src/rtl/p3utils.h
        src/rtl/sysutils_p3.cpp
        src/rtl/sysutils_p3.h
        src/rtl/system_p3.cpp
        src/rtl/system_p3.h
        src/rtl/p3platform.cpp
        src/rtl/p3platform.h
        src/rtl/math_p3.cpp
        src/rtl/math_p3.h
        src/rtl/idglobal_p3.cpp
        src/rtl/idglobal_p3.h
        src/rtl/p3io.cpp
        src/rtl/p3io.h
        src/rtl/dtoaLoc.c
        src/rtl/dtoaLoc.h

        # global
        src/global/ctvproc.cpp
        src/global/ctvproc.h
        src/global/delphitypes.h
        src/global/gmslibname.cpp
        src/global/gmslibname.h
        src/global/gmsspecs.cpp
        src/global/gmsspecs.h
        src/global/unit.h
        src/global/modhead.cpp
        src/global/modhead.h

        # gdlib
        src/gdlib/batchalloc.h
        src/gdlib/charmaps.cpp
        src/gdlib/charmaps.h
        src/gdlib/cmdpar.cpp
        src/gdlib/cmdpar.h
        src/gdlib/datastorage.cpp
        src/gdlib/datastorage.h
        src/gdlib/dblutil.cpp
        src/gdlib/dblutil.h
        src/gdlib/gamsdirs.cpp
        src/gdlib/gamsdirs.h
        src/gdlib/gfileopen.cpp
        src/gdlib/gfileopen.h
        src/gdlib/glookup.cpp
        src/gdlib/glookup.h
        src/gdlib/gmacro.cpp
        src/gdlib/gmacro.h
        src/gdlib/gmsdata.cpp
        src/gdlib/gmsdata.h
        src/gdlib/gmsgen.h
        src/gdlib/gmsglob.cpp
        src/gdlib/gmsglob.h
        src/gdlib/gmslist.cpp
        src/gdlib/gmslist.h
        src/gdlib/gmsobj.cpp
        src/gdlib/gmsobj.h
        src/gdlib/obfuscatestr.cpp
        src/gdlib/obfuscatestr.h
        src/gdlib/runner.cpp
        src/gdlib/runner.h
        src/gdlib/statlib.cpp
        src/gdlib/statlib.h
        src/gdlib/statlibobj.cpp
        src/gdlib/statlibobj.h
        src/gdlib/stattypes.h
        src/gdlib/xcompress.cpp
        src/gdlib/xcompress.h
        src/gdlib/gmsheapnew.cpp
        src/gdlib/gmsheapnew.h
        src/gdlib/strutilx.cpp
        src/gdlib/strutilx.h
        src/gdlib/strhash.cpp
        src/gdlib/strhash.h
        src/gdlib/gmsonly.h
        src/gdlib/gmsonly.cpp
)