# also includes unused sources (modules and headers)
set(base-units-all
    # runtime library
    ${CMAKE_SOURCE_DIR}/src/rtl/p3library.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3library.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3process.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3process.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/stdthread.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/stdthread.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3utils.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3utils.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/sysutils_p3.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/sysutils_p3.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/system_p3.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/system_p3.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3platform.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3platform.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/math_p3.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/math_p3.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/idglobal_p3.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/idglobal_p3.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3io.cpp
    ${CMAKE_SOURCE_DIR}/src/rtl/p3io.hpp
    ${CMAKE_SOURCE_DIR}/src/rtl/dtoaLoc.c
    ${CMAKE_SOURCE_DIR}/src/rtl/dtoaLoc.h

    # global
    ${CMAKE_SOURCE_DIR}/src/global/ctvproc.cpp
    ${CMAKE_SOURCE_DIR}/src/global/ctvproc.hpp
    ${CMAKE_SOURCE_DIR}/src/global/delphitypes.hpp
    ${CMAKE_SOURCE_DIR}/src/global/gmslibname.cpp
    ${CMAKE_SOURCE_DIR}/src/global/gmslibname.hpp
    ${CMAKE_SOURCE_DIR}/src/global/gmsspecs.cpp
    ${CMAKE_SOURCE_DIR}/src/global/gmsspecs.hpp
    ${CMAKE_SOURCE_DIR}/src/global/unit.h
    ${CMAKE_SOURCE_DIR}/src/global/modhead.cpp
    ${CMAKE_SOURCE_DIR}/src/global/modhead.hpp

    # gdlib
    ${CMAKE_SOURCE_DIR}/src/gdlib/batchalloc.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/charmaps.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/charmaps.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/cmdpar.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/cmdpar.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/datastorage.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/datastorage.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/dblutil.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/dblutil.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gamsdirs.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gamsdirs.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gfileopen.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gfileopen.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/glookup.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/glookup.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmacro.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmacro.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsdata.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsdata.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsgen.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsglob.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsglob.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmslist.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmslist.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsobj.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsobj.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/obfuscatestr.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/obfuscatestr.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/runner.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/runner.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/statlib.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/statlib.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/statlibobj.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/statlibobj.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/stattypes.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/xcompress.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/xcompress.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsheapnew.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsheapnew.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/strutilx.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/strutilx.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/strhash.cpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/strhash.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsonly.hpp
    ${CMAKE_SOURCE_DIR}/src/gdlib/gmsonly.cpp
)
