/*
* GAMS - General Algebraic Modeling System GDX API
*
* Copyright (c) 2017-2026 GAMS Software GmbH <support@gams.com>
* Copyright (c) 2017-2026 GAMS Development Corp. <support@gams.com>
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

// This is entirely LLM-generated by Claude Opus 5.5

#if !defined( _WIN32 )

#include <array>
#include <cfenv>
#include <cfloat>
#include <cmath>
#include <csetjmp>
#include <csignal>
#if defined( __x86_64__ ) || defined( __i386__ )
#include <xmmintrin.h>
#endif
#include <ostream>
#include <string>

#include "math_p3.hpp"
#include "../doctest.hpp"

using namespace rtl::math_p3;

namespace tests::rtltests::mathp3tests
{

TEST_SUITE_BEGIN( "rtl::mathp3tests" );

static volatile std::sig_atomic_t sigfpeCaught {};
static sigjmp_buf jmpEnv;

static void sigfpeHandler( int )
{
   sigfpeCaught = 1;
   // returning would re-execute the faulting instruction, so jump over it
   siglongjmp( jmpEnv, 1 );
}

// volatile operands prevent the compiler from constant folding the operations
static volatile double vZero = 0.0, vOne = 1.0, vThree = 3.0, vMinusOne = -1.0;
static volatile double vMax = DBL_MAX, vMin = DBL_MIN, vDenorm = DBL_MIN / 4;
static volatile double vRes;

static void opInvalid() { vRes = vZero / vZero; }
static void opDenormal() { vRes = vDenorm * vOne; }
static void opZeroDivide() { vRes = vOne / vZero; }
static void opOverflow() { vRes = vMax * vThree; }
static void opUnderflow() { vRes = vMin / vThree; }
static void opPrecision() { vRes = vOne / vThree; }
static void opSqrtInvalid() { vRes = std::sqrt( vMinusOne ); }

struct FPECase {
   TFPUException ex;
   const char *name;
   void ( *op )();
};

static const std::array<FPECase, 7> fpeCases { {
        { exInvalidOp, "exInvalidOp (0/0)", opInvalid },
        { exInvalidOp, "exInvalidOp (sqrt(-1))", opSqrtInvalid },
        { exDenormalized, "exDenormalized", opDenormal },
        { exZeroDivide, "exZeroDivide", opZeroDivide },
        { exOverflow, "exOverflow", opOverflow },
        { exUnderflow, "exUnderflow", opUnderflow },
        { exPrecision, "exPrecision", opPrecision },
} };

// Saves the FPE mask and installs the SIGFPE handler, restores both on destruction
class FPEGuard
{
   TFPUExceptionMask savedMask;
   struct sigaction oldAction {};

public:
   FPEGuard() : savedMask { GetExceptionMask() }
   {
      struct sigaction sa {};
      sa.sa_handler = sigfpeHandler;
      sigemptyset( &sa.sa_mask );
      sigaction( SIGFPE, &sa, &oldAction );
   }

   ~FPEGuard()
   {
      ClearExceptions();
      SetExceptionMask( savedMask );
      sigaction( SIGFPE, &oldAction, nullptr );
   }
};

// Returns true iff performing op raised SIGFPE under the given FPE mask
static bool raisesSIGFPE( const TFPUExceptionMask &mask, void ( *op )() )
{
   sigfpeCaught = 0;
   ClearExceptions();
   // set the mask after sigsetjmp: the kernel resets the FP environment when entering the handler
   // savemask=1 so that SIGFPE is unblocked again after the siglongjmp out of the handler
   if( !sigsetjmp( jmpEnv, 1 ) )
   {
      SetExceptionMask( mask );
      op();
   }
   ClearExceptions();
   return sigfpeCaught;
}

static TFPUExceptionMask allMasked()
{
   TFPUExceptionMask m {};
   for( auto ex: { exInvalidOp, exDenormalized, exZeroDivide, exOverflow, exUnderflow, exPrecision } )
      m.set( ex );
   return m;
}

// Trapping FPEs is optional on aarch64: on CPUs without support, unmasking has no effect
static bool trapsSupported()
{
#if defined( __aarch64__ )
   FPEGuard guard;
   SetExceptionMask( TFPUExceptionMask {} );
   const bool supported = !GetExceptionMask().test( exZeroDivide );
   if( !supported ) MESSAGE( "FPE trapping not supported by this CPU, skipping unmasking checks" );
   return supported;
#else
   return true;
#endif
}

// The denormal operand exception cannot always be unmasked (e.g. glibc does not support it), and never
// triggers when denormal operands are treated as zero (DAZ bit in MXCSR, e.g. set by -ffast-math)
static bool denormalTrapSupported( const TFPUExceptionMask &mask )
{
   FPEGuard guard;
   SetExceptionMask( mask );
   if( GetExceptionMask().test( exDenormalized ) )
   {
      MESSAGE( "Unmasking exDenormalized not supported, skipping its check" );
      return false;
   }
#if defined( __x86_64__ ) || defined( __i386__ )
   if( _mm_getcsr() & ( 1u << 6 ) )
   {
      MESSAGE( "Denormals are treated as zero (DAZ), skipping exDenormalized check" );
      return false;
   }
#endif
   return true;
}

TEST_CASE( "Set/GetExceptionMask round trip" )
{
   if( !trapsSupported() ) return;
   FPEGuard guard;
   const auto initial = GetExceptionMask();
   const auto all = allMasked();

   auto m = all;
   m.reset( exZeroDivide );
   m.reset( exOverflow );
   REQUIRE_EQ( SetExceptionMask( m ), initial );
   REQUIRE_EQ( GetExceptionMask(), m );
   REQUIRE_EQ( SetExceptionMask( all ), m );
   REQUIRE_EQ( GetExceptionMask(), all );
}

TEST_CASE( "Masked IEEE-754 exceptions do not raise SIGFPE" )
{
   FPEGuard guard;
   for( const auto &c: fpeCases )
   {
      CHECK_FALSE_MESSAGE( raisesSIGFPE( allMasked(), c.op ),
                           std::string { c.name } << ": SIGFPE raised although all FPEs are masked" );
   }
}

TEST_CASE( "Unmasked IEEE-754 exceptions raise SIGFPE" )
{
   if( !trapsSupported() ) return;
   FPEGuard guard;
   for( const auto &c: fpeCases )
   {
      auto m = allMasked();
      m.reset( c.ex );
      if( c.ex == exDenormalized && !denormalTrapSupported( m ) ) continue;
      // On x86-64, SSE arithmetic on doubles is governed by MXCSR, not by the x87 control word
      CHECK_MESSAGE( raisesSIGFPE( m, c.op ),
                     std::string { c.name } << ": no SIGFPE raised although unmasked. ");
   }
}

TEST_SUITE_END();

}// namespace tests::rtltests::mathp3tests

#endif
