/*
* GAMS - General Algebraic Modeling System GDX API
*
* Copyright (c) 2017-2026 GAMS Software GmbH <support@gams.com>
* Copyright (c) 2017-2026 GAMS Development Corp. <support@gams.com>
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

// This is entirely LLM-generated by Claude Opus 5.5

#include <array>
#include <cfenv>
#include <cfloat>
#include <cmath>
#include <cstdio>
#if defined( _WIN32 )
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#else
#include <csetjmp>
#include <csignal>
#endif
#if defined( __x86_64__ ) || defined( __i386__ ) || defined( _M_X64 ) || defined( _M_IX86 )
#define MATHP3TESTS_X86
#include <xmmintrin.h>
#endif
#include <ostream>
#include <string>

#include "math_p3.hpp"
#include "../doctest.hpp"

using namespace rtl::math_p3;

namespace tests::rtltests::mathp3tests
{

TEST_SUITE_BEGIN( "rtl::mathp3tests" );

// volatile operands prevent the compiler from constant folding the operations
static volatile double vZero = 0.0, vOne = 1.0, vThree = 3.0;
static volatile double vMax = DBL_MAX, vMin = DBL_MIN, vDenorm = DBL_MIN / 4;
static volatile double vRes;

static void opInvalid() { vRes = vZero / vZero; }
static void opDenormal() { vRes = vDenorm * vOne; }
static void opZeroDivide() { vRes = vOne / vZero; }
static void opOverflow() { vRes = vMax * vThree; }
static void opUnderflow() { vRes = vMin / vThree; }
static void opPrecision() { vRes = vOne / vThree; }
#if !defined( __MINGW32__ )
static volatile double vMinusOne = -1.0;
static void opSqrtInvalid() { vRes = std::sqrt( vMinusOne ); }
#endif

struct FPECase {
   TFPUException ex;
   const char *name;
   void ( *op )();
};

static const FPECase fpeCases[] {
        { exInvalidOp, "exInvalidOp (0/0)", opInvalid },
#if !defined( __MINGW32__ )
        // MinGW-w64's sqrt returns NaN for negative arguments without executing an FP instruction,
        // hence no FPE is raised whatever the mask
        { exInvalidOp, "exInvalidOp (sqrt(-1))", opSqrtInvalid },
#endif
        { exDenormalized, "exDenormalized", opDenormal },
        { exZeroDivide, "exZeroDivide", opZeroDivide },
        { exOverflow, "exOverflow", opOverflow },
        { exUnderflow, "exUnderflow", opUnderflow },
        { exPrecision, "exPrecision", opPrecision },
};

#if defined( _WIN32 )

// Windows reports FP traps as structured exceptions. The vectored handler is called before any
// frame-based handler and before doctest's unhandled exception filter
static volatile LONG fpeCaught {};
static volatile DWORD fpeCode {};

static LONG WINAPI fpeHandler( EXCEPTION_POINTERS *info )
{
   switch( info->ExceptionRecord->ExceptionCode )
   {
      case EXCEPTION_FLT_DENORMAL_OPERAND:
      case EXCEPTION_FLT_DIVIDE_BY_ZERO:
      case EXCEPTION_FLT_INEXACT_RESULT:
      case EXCEPTION_FLT_INVALID_OPERATION:
      case EXCEPTION_FLT_OVERFLOW:
      case EXCEPTION_FLT_STACK_CHECK:
      case EXCEPTION_FLT_UNDERFLOW:
      case STATUS_FLOAT_MULTIPLE_FAULTS:
      case STATUS_FLOAT_MULTIPLE_TRAPS:
         break;
      default:
         return EXCEPTION_CONTINUE_SEARCH;
   }
   fpeCaught = 1;
   fpeCode = info->ExceptionRecord->ExceptionCode;

   // Mask all exceptions and clear the status flags in the saved context, so that the faulting
   // instruction is re-executed without trapping when execution continues
   CONTEXT *ctx = info->ContextRecord;
#if defined( _M_X64 ) || defined( __x86_64__ )
   ctx->MxCsr = ( ctx->MxCsr | 0x1f80 ) & ~0x3fu;
   ctx->FltSave.MxCsr = ctx->MxCsr;
   ctx->FltSave.ControlWord |= 0x3f;
   ctx->FltSave.StatusWord &= ~0xbf;
#elif defined( _M_IX86 ) || defined( __i386__ )
   ctx->FloatSave.ControlWord |= 0x3f;
   ctx->FloatSave.StatusWord &= ~0xbf;
#elif defined( _M_ARM64 ) || defined( __aarch64__ )
   ctx->Fpcr &= ~0x9f00u;
   ctx->Fpsr &= ~0x9fu;
#endif
   return EXCEPTION_CONTINUE_EXECUTION;
}

// Saves the FPE mask and installs the FPE exception handler, restores both on destruction
class FPEGuard
{
   TFPUExceptionMask savedMask;
   PVOID handler;

public:
   FPEGuard() : savedMask { GetExceptionMask() }, handler { AddVectoredExceptionHandler( 1, fpeHandler ) }
   {
   }

   ~FPEGuard()
   {
      ClearExceptions();
      SetExceptionMask( savedMask );
      RemoveVectoredExceptionHandler( handler );
   }
};

// Returns true iff performing op raised an FPE under the given FPE mask
static bool raisesFPE( const TFPUExceptionMask &mask, void ( *op )() )
{
   fpeCaught = 0;
   fpeCode = 0;
   ClearExceptions();
   SetExceptionMask( mask );
   op();
   ClearExceptions();
   return fpeCaught;
}

// Checks that the reported exception code corresponds to the unmasked exception
static void checkFPECode( TFPUException ex, const char *name )
{
   DWORD expected {};
   switch( ex )
   {
      case exInvalidOp: expected = EXCEPTION_FLT_INVALID_OPERATION; break;
      case exDenormalized: expected = EXCEPTION_FLT_DENORMAL_OPERAND; break;
      case exZeroDivide: expected = EXCEPTION_FLT_DIVIDE_BY_ZERO; break;
      case exOverflow: expected = EXCEPTION_FLT_OVERFLOW; break;
      case exUnderflow: expected = EXCEPTION_FLT_UNDERFLOW; break;
      case exPrecision: expected = EXCEPTION_FLT_INEXACT_RESULT; break;
   }
   // SSE faults may also be reported without detail
   const DWORD code = fpeCode;
   char hexCode[16];
   std::snprintf( hexCode, sizeof( hexCode ), "0x%08lx", static_cast<unsigned long>( code ) );
   CHECK_MESSAGE( ( code == expected || code == STATUS_FLOAT_MULTIPLE_FAULTS || code == STATUS_FLOAT_MULTIPLE_TRAPS ),
                  std::string { name } << ": unexpected exception code " << hexCode );
}

#else

static volatile std::sig_atomic_t fpeCaught {};
static sigjmp_buf jmpEnv;

static void fpeHandler( int )
{
   fpeCaught = 1;
   // returning would re-execute the faulting instruction, so jump over it
   siglongjmp( jmpEnv, 1 );
}

// macOS on arm64 delivers floating-point traps as SIGILL instead of SIGFPE
// NOTE: keeping this as an std::array in case SIGFPE is raised on some platform
// at some point --OH
#if defined( __APPLE__ ) && defined( __arm64__ )
static constexpr std::array fpeSignals { SIGILL };
#else
static constexpr std::array fpeSignals { SIGFPE };
#endif

// Saves the FPE mask and installs the FPE signal handler, restores both on destruction
class FPEGuard
{
   TFPUExceptionMask savedMask;
   std::array<struct sigaction, fpeSignals.size()> oldActions {};

public:
   FPEGuard() : savedMask { GetExceptionMask() }
   {
      struct sigaction sa {};
      sa.sa_handler = fpeHandler;
      sigemptyset( &sa.sa_mask );
      for( size_t i {}; i < fpeSignals.size(); i++ )
         sigaction( fpeSignals[i], &sa, &oldActions[i] );
   }

   ~FPEGuard()
   {
      ClearExceptions();
      SetExceptionMask( savedMask );
      for( size_t i {}; i < fpeSignals.size(); i++ )
         sigaction( fpeSignals[i], &oldActions[i], nullptr );
   }
};

// Returns true iff performing op raised an FPE under the given FPE mask
static bool raisesFPE( const TFPUExceptionMask &mask, void ( *op )() )
{
   fpeCaught = 0;
   ClearExceptions();
   // set the mask after sigsetjmp: the kernel resets the FP environment when entering the handler
   // savemask=1 so that SIGFPE is unblocked again after the siglongjmp out of the handler
   if( !sigsetjmp( jmpEnv, 1 ) )
   {
      SetExceptionMask( mask );
      op();
   }
   ClearExceptions();
   return fpeCaught;
}

static void checkFPECode( TFPUException, const char * ) {}// no exception details with signals

#endif

static TFPUExceptionMask allMasked()
{
   TFPUExceptionMask m {};
   for( auto ex: { exInvalidOp, exDenormalized, exZeroDivide, exOverflow, exUnderflow, exPrecision } )
      m.set( ex );
   return m;
}

// Trapping FPEs is optional on aarch64: on CPUs without support, unmasking has no effect
static bool trapsSupported()
{
#if defined( __aarch64__ ) || defined( _M_ARM64 )
   FPEGuard guard;
   SetExceptionMask( TFPUExceptionMask {} );
   const bool supported = !GetExceptionMask().test( exZeroDivide );
   if( !supported ) MESSAGE( "FPE trapping not supported by this CPU, skipping unmasking checks" );
   return supported;
#else
   return true;
#endif
}

// The denormal operand exception cannot always be unmasked (e.g. glibc does not support it), and never
// triggers when denormal operands are treated as zero (DAZ bit in MXCSR, e.g. set by -ffast-math)
static bool denormalTrapSupported( const TFPUExceptionMask &mask )
{
   FPEGuard guard;
   SetExceptionMask( mask );
   if( GetExceptionMask().test( exDenormalized ) )
   {
      MESSAGE( "Unmasking exDenormalized not supported, skipping its check" );
      return false;
   }
#if defined( MATHP3TESTS_X86 )
   if( _mm_getcsr() & ( 1u << 6 ) )
   {
      MESSAGE( "Denormals are treated as zero (DAZ), skipping exDenormalized check" );
      return false;
   }
#endif
   return true;
}

TEST_CASE( "Set/GetExceptionMask round trip" )
{
   if( !trapsSupported() ) return;
   FPEGuard guard;
   const auto initial = GetExceptionMask();
   const auto all = allMasked();

   auto m = all;
   m.reset( exZeroDivide );
   m.reset( exOverflow );
   REQUIRE_EQ( SetExceptionMask( m ), initial );
   REQUIRE_EQ( GetExceptionMask(), m );
   REQUIRE_EQ( SetExceptionMask( all ), m );
   REQUIRE_EQ( GetExceptionMask(), all );
}

TEST_CASE( "Masked IEEE-754 exceptions do not raise an FPE" )
{
   FPEGuard guard;
   for( const auto &c: fpeCases )
   {
      CHECK_FALSE_MESSAGE( raisesFPE( allMasked(), c.op ),
                           std::string { c.name } << ": FPE raised although all FPEs are masked" );
   }
}

TEST_CASE( "Unmasked IEEE-754 exceptions raise an FPE" )
{
   if( !trapsSupported() ) return;
   FPEGuard guard;
   for( const auto &c: fpeCases )
   {
      auto m = allMasked();
      m.reset( c.ex );
      if( c.ex == exDenormalized && !denormalTrapSupported( m ) ) continue;
      // On x86-64, SSE arithmetic on doubles is governed by MXCSR, not by the x87 control word
      const bool raised = raisesFPE( m, c.op );
      CHECK_MESSAGE( raised, std::string { c.name } << ": no FPE raised although unmasked. " );
      if( raised ) checkFPECode( c.ex, c.name );
   }
}

TEST_SUITE_END();

}// namespace tests::rtltests::mathp3tests
